// Generated by CoffeeScript 1.12.5
(function() {
  $(function() {
    $('.js-swipeList').swipeList();
    $('.js-swipeList2').swipeList({
      direction: 'right'
    });
    $('.js-swipeList3').swipeList({
      speed: 1000
    });
    $('.js-swipeList4').swipeList({
      easing: 'ease-in'
    });
  });

  $(function() {
    var body, menu, menuBtn, menuWidth;
    menu = $('#slide_menu');
    menuBtn = $('#button');
    body = $(document.body);
    menuWidth = menu.outerWidth();
    menuBtn.on('click', function() {
      body.toggleClass('open');
      if (body.hasClass('open')) {
        body.animate({
          'left': menuWidth
        }, 300);
        menu.animate({
          'left': 0
        }, 300);
      } else {
        menu.animate({
          'left': -menuWidth
        }, 300);
        body.animate({
          'left': 0
        }, 300);
      }
    });
  });

  $(function() {
    var haba, syncTimeout;
    syncTimeout = null;
    $(window).scroll(function() {
      $('#button').fadeOut('fast');
      $('#page-top').fadeOut('fast');
      if (syncTimeout === null) {
        syncTimeout = setTimeout((function() {
          var TopScroll, visible, wnHeight;
          TopScroll = $(window).scrollTop();
          $('#button').css('top', TopScroll);
          $('#button').fadeIn('slow');
          visible = $('#page-top').is(':visible');
          wnHeight = $(window).height();
          if (TopScroll > 1000) {
            if (!visible) {
              $('#page-top').css('top', TopScroll + wnHeight - 80);
              $('#page-top').fadeIn('slow');
            }
          }
          syncTimeout = null;
        }), 1500);
      }
    });
    $('#move-page-top').click(function() {
      $('html,body').animate({
        scrollTop: 0
      }, 'slow');
    });
    if ($(window).width() > 481) {
      haba = $('.list-contents').width();
      $('.title').css('width', haba - 150);
    }
  });

}).call(this);
