# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# スワイプリスト

$ ->
  $('.js-swipeList').swipeList()
  $('.js-swipeList2').swipeList direction: 'right'
  $('.js-swipeList3').swipeList speed: 1000
  $('.js-swipeList4').swipeList easing: 'ease-in'
  return

# スライドメニュー
# SlideIn_Menu

$ ->
  menu = $('#slide_menu')
  menuBtn = $('#button')
  body = $(document.body)
  menuWidth = menu.outerWidth()
  menuBtn.on 'click', ->
    body.toggleClass 'open'
    if body.hasClass('open')
      body.animate { 'left': menuWidth }, 300
      menu.animate { 'left': 0 }, 300
    else
      menu.animate { 'left': -menuWidth }, 300
      body.animate { 'left': 0 }, 300
    return
  return

# メニューボタン・トップへ戻るボタン

$ ->
  syncTimeout = null
  # nullをセット
  $(window).scroll ->
    $('#button').fadeOut 'fast'
    # すぐに消える
    $('#page-top').fadeOut 'fast'
    if syncTimeout == null
      # 一定の時間の後に次の処理をおこなう
      syncTimeout = setTimeout((->
        # メニューボタンの処理
        TopScroll = $(window).scrollTop()
        # スクロール量
        $('#button').css 'top', TopScroll
        $('#button').fadeIn 'slow'
        # じわっと現れる
        # 戻るボタンの処理
        # 現在表示されているか？
        visible = $('#page-top').is(':visible')
        wnHeight = $(window).height()
        # 画面の高さ
        # 最上部から現在位置までの距離TopScrollが1000px以上だったら
        if TopScroll > 1000
          if !visible
            $('#page-top').css 'top', TopScroll + wnHeight - 80
            $('#page-top').fadeIn 'slow'
            # じんわり出現
        syncTimeout = null
        return
      ), 1500)
      # 1.5秒後
    return
  $('#move-page-top').click ->
    $('html,body').animate { scrollTop: 0 }, 'slow'
    return
  if $(window).width() > 481
    haba = $('.list-contents').width()
    $('.title').css 'width', haba - 150
  return


# ---
# generated by js2coffee 2.1.0